export const poolTables = [
    {
      id: 1,
      type:"pool",
      title: "Alessia",
      image: "/assets/poolTables/alessia.png",
      description: "Mesa de billar estilo clásico italiano.",
    },
    {
      id: 2,
      type:"pool",
      title: "Alison",
      image: "/assets/poolTables/alison.png",
      description: "Diseño moderno con acabados en negro.",
    },
    {
      id: 3,
      type:"pool",
      title: "Arabia",
      image: "/assets/poolTables/arabia.png",
      description: "Inspirada en patrones orientales.",
    },
    {
      id: 4,
      type:"pool",
      title: "Bulgaria",
      image: "/assets/poolTables/bulgaria.png",
      description: "Estilo rústico con detalles balcánicos.", 
    },
    {
      id: 5,
      type:"pool",
      title: "Copenhague",
      image: "/assets/poolTables/copenhague.png",
      description: "Diseño minimalista inspirado en Dinamarca.",  
    },
    {
        id: 6,
        type:"pool",
        title: "Cubana",
        image: "/assets/poolTables/cubana.png",
        description: "Colores vibrantes y aire tropical.", 
      },
      {
        id: 7,
        type:"pool",
        title: "Dinamarca",
        image: "/assets/poolTables/dinamarca.png",
        description: "Líneas limpias y funcionales.",  
      },
      {
        id: 8,
        type:"pool",
        title: "Doblex",
        image: "/assets/poolTables/doblex.png",
        description: "Mesa con base cruzada para partidas intensas.",  
      },
      {
        id: 9,
        type:"pool",
        title: "Eliminator",
        image: "/assets/poolTables/eliminator.png",
        description: "Estilo competitivo con acabados metálicos.",  
      },
      {
        id: 10,
        type:"pool",
        title: "Emily",
        image: "/assets/poolTables/emily.png",
        description: "Elegancia clásica con toques vintage.",    
      },
      {
        id: 11,
        type:"pool",
        title: "Ginevra",
        image: "/assets/poolTables/ginevra.png",
        description: "Lujo suizo con madera tallada.",  
      },
      {
        id: 12,
        type:"pool",
        title: "Grecia",
        image: "/assets/poolTables/grecia.png",
        description: "Influencia mediterránea en azules y blancos.",  
      },
      {
        id: 13,
        type:"pool",
        title: "Mali",
        image: "/assets/poolTables/mali.jpeg",
        description: "Patrones africanos y colores tierra.",  
      },
      {
        id: 14,
        type:"pool",
        title: "Miami Monedas",
        image: "/assets/poolTables/miamiMonedas.png",
        description: "Estilo art déco años 80.",  
      },
      {
        id: 15,
        type:"pool",
        title: "Mondas",
        image: "/assets/poolTables/mondas.png",
        description: "Acabados modernos en tonos neutros.",  
      },
      {
        id: 16,
        type:"pool",
        title: "Monterrey",
        image: "/assets/poolTables/monterrey.png",
        description: "Robusta y con detalles mexicanos.",  
      },
      {
        id: 17,
        type:"pool",
        title: "Olimpia",
        image: "/assets/poolTables/olimpia.png",
        description: "Inspirada del olimpo griego.",  
      },
      {
        id: 18,
        type:"pool",
        title: "Pop",
        image: "/assets/poolTables/pop.png",
        description: "retro y clase en una mesa",
      },
      {
        id: 19,
        type:"pool",
        title: "San Antonio",
        image: "/assets/poolTables/sanAntonio.png",
        description: "Estilo tejano con detalles western.",    
      },
      {
        id: 20,
        type:"pool",
        title: "Tokio",
        image: "/assets/poolTables/tokio.jpeg",
        description: "Futurista con influencia japonesa.",  
      },
      {
        id: 21,
        type:"pool",
        title: "Tower",
        image: "/assets/poolTables/tower.png",
        description: "Lo clasico del oeste",
      },
      {
        id: 22,
        type:"pool",
        title: "Uganda",
        image: "/assets/poolTables/uganda.png",
        description: "Patrones étnicos y maderas oscuras.",  
      },
      {
        id: 23,
        type:"pool",
        title: "Urus",
        image: "/assets/poolTables/urus.jpeg",
        description: "Lujo moderno con inspiración automotriz.",  
      },
      {
        id: 24,
        type:"pool",
        title: "Venecia",
        image: "/assets/poolTables/venecia.png",
        description: "Paseo por esos canales rusticos",  
      },
  ];