export const poolTables = [
    {
      id: 1,
      type:"pool",
      title: "Alessia",
      image: "/images/pool/alessia.png",
      description: "Mesa de billar estilo clásico italiano.",
    },
    {
      id: 2,
      type:"pool",
      title: "Alison",
      image: "/images/pool/alison.png",
      description: "Diseño moderno con acabados en negro.",
    },
    {
      id: 3,
      type:"pool",
      title: "Arabia",
      image: "/images/pool/arabia.png",
      description: "Inspirada en patrones orientales.",
    },
    {
      id: 4,
      type:"pool",
      title: "Bulgaria",
      image: "/images/pool/bulgaria.png",
      description: "Estilo rústico con detalles balcánicos.", 
    },
    {
      id: 5,
      type:"pool",
      title: "Copenhague",
      image: "/images/pool/copenhague.png",
      description: "Diseño minimalista inspirado en Dinamarca.",  
    },
    {
        id: 6,
        type:"pool",
        title: "Cubana",
        image: "/images/pool/cubana.png",
        description: "Colores vibrantes y aire tropical.", 
      },
      {
        id: 7,
        type:"pool",
        title: "Dinamarca",
        image: "/images/pool/dinamarca.png",
        description: "Líneas limpias y funcionales.",  
      },
      {
        id: 8,
        type:"pool",
        title: "Doblex",
        image: "/images/pool/doblex.png",
        description: "Mesa con base cruzada para partidas intensas.",  
      },
      {
        id: 9,
        type:"pool",
        title: "Eliminator",
        image: "/images/pool/eliminator.png",
        description: "Estilo competitivo con acabados metálicos.",  
      },
      {
        id: 10,
        type:"pool",
        title: "Emily",
        image: "/images/pool/emily.png",
        description: "Elegancia clásica con toques vintage.",    
      },
      {
        id: 11,
        type:"pool",
        title: "Ginevra",
        image: "/images/pool/ginevra.png",
        description: "Lujo suizo con madera tallada.",  
      },
      {
        id: 12,
        type:"pool",
        title: "Grecia",
        image: "/images/pool/grecia.png",
        description: "Influencia mediterránea en azules y blancos.",  
      },
      {
        id: 13,
        type:"pool",
        title: "Mali",
        image: "/images/pool/mali.jpeg",
        description: "Patrones africanos y colores tierra.",  
      },
      {
        id: 14,
        type:"pool",
        title: "Miami Monedas",
        image: "/images/pool/miamiMonedas.png",
        description: "Estilo art déco años 80.",  
      },
      {
        id: 15,
        type:"pool",
        title: "Mondas",
        image: "/images/pool/mondas.png",
        description: "Acabados modernos en tonos neutros.",  
      },
      {
        id: 16,
        type:"pool",
        title: "Monterrey",
        image: "/images/pool/monterrey.png",
        description: "Robusta y con detalles mexicanos.",  
      },
      {
        id: 17,
        type:"pool",
        title: "Olimpia",
        image: "/images/pool/olimpia.png",
        description: "Inspirada del olimpo griego.",  
      },
      {
        id: 18,
        type:"pool",
        title: "Pop",
        image: "/images/pool/pop.png",
        description: "retro y clase en una mesa",
      },
      {
        id: 19,
        type:"pool",
        title: "San Antonio",
        image: "/images/pool/sanAntonio.png",
        description: "Estilo tejano con detalles western.",    
      },
      {
        id: 20,
        type:"pool",
        title: "Tokio",
        image: "/images/pool/tokio.jpeg",
        description: "Futurista con influencia japonesa.",  
      },
      {
        id: 21,
        type:"pool",
        title: "Tower",
        image: "/images/pool/tower.png",
        description: "Lo clasico del oeste",
      },
      {
        id: 22,
        type:"pool",
        title: "Uganda",
        image: "/images/pool/uganda.png",
        description: "Patrones étnicos y maderas oscuras.",  
      },
      {
        id: 23,
        type:"pool",
        title: "Urus",
        image: "/images/pool/urus.png",
        description: "Lujo moderno con inspiración automotriz.",  
      },
      {
        id: 24,
        type:"pool",
        title: "Venecia",
        image: "/images/pool/venecia.png",
        description: "Paseo por esos canales rusticos",  
      },
  ];
