export const soccerTables = [
  {
    id: 1,
    type: "soccer",
    title: "Albino",
    image: "/assets/soccer/albino.png",
    description: "Futbolito de diseño limpio y moderno.",
  },
  {
    id: 2,
    type: "soccer",
    title: "Arco",
    image: "/assets/soccer/arco.png",
    description: "Futbolito con estructura arqueada que resalta por su elegancia.",
  },
  {
    id: 3,
    type: "soccer",
    title: "Carreta",
    image: "/assets/soccer/carreta.png",
    description: "Diseño rústico con ruedas decorativas, ideal para exteriores.",
  },
  {
    id: 4,
    type: "soccer",
    title: "Chocolate",
    image: "/assets/soccer/chocolate.png",
    description: "Acabado en tonos marrón oscuro, sofisticado y cálido.",
  },
  {
    id: 5,
    type: "soccer",
    title: "Clásico",
    image: "/assets/soccer/clasico.png",
    description: "Futbolito tradicional con diseño atemporal.",
  },
  {
    id: 6,
    type: "soccer",
    title: "Con Mecanismo",
    image: "/assets/soccer/conMecanismo.png",
    description: "Incluye mecanismos especiales para mayor funcionalidad.",
  },
  {
    id: 7,
    type: "soccer",
    title: "Futbolito de Lujo",
    image: "/assets/soccer/futbolitoDeLujo.png",
    description: "Mesa de lujo con detalles premium y acabados exclusivos.",
  },
  {
    id: 8,
    type: "soccer",
    title: "Monopoli",
    image: "/assets/soccer/monopoli.png",
    description: "Estilo creativo inspirado en el juego Monopoly.",
  },
  {
    id: 9,
    type: "soccer",
    title: "Soccer Table",
    image: "/assets/soccer/soccerTable.png",
    description: "Futbolito estándar para juegos familiares y torneos.",
  },
  {
    id: 10,
    type: "soccer",
    title: "Tokio",
    image: "/assets/soccer/tokio.png",
    description: "Diseño moderno con inspiración japonesa minimalista.",
  },
  {
    id: 11,
    type: "soccer",
    title: "Turco",
    image: "/assets/soccer/turco.png",
    description: "Mesa de futbolito con estilo oriental y detalles artesanales.",
  },
  {
    id: 12,
    type: "soccer",
    title: "Uso Rudo",
    image: "/assets/soccer/usoRudo.png",
    description: "Diseñada para alto tráfico y resistencia máxima.",
  },
  {
    id: 13,
    type: "soccer",
    title: "Vintage",
    image: "/assets/soccer/vintage.png",
    description: "Mesa retro con encanto clásico y detalles antiguos.",
  },
];
